# syntax=docker/dockerfile:1
FROM golang:1.21-alpine AS builder

WORKDIR /proxy
COPY proxy/go.mod proxy/go.sum ./
RUN go mod download

COPY proxy/ ./
COPY shared/ ../shared/

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /app/proxy ./cmd

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/proxy .
EXPOSE 25565
ENTRYPOINT ["./proxy"]
