// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: pkg/proto/coordinator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoordinatorService_RegisterShard_FullMethodName         = "/shardedmc.CoordinatorService/RegisterShard"
	CoordinatorService_SendHeartbeat_FullMethodName         = "/shardedmc.CoordinatorService/SendHeartbeat"
	CoordinatorService_RequestPlayerTransfer_FullMethodName = "/shardedmc.CoordinatorService/RequestPlayerTransfer"
	CoordinatorService_ConfirmPlayerTransfer_FullMethodName = "/shardedmc.CoordinatorService/ConfirmPlayerTransfer"
	CoordinatorService_RequestChunkLoad_FullMethodName      = "/shardedmc.CoordinatorService/RequestChunkLoad"
	CoordinatorService_RequestChunkUnload_FullMethodName    = "/shardedmc.CoordinatorService/RequestChunkUnload"
	CoordinatorService_RequestChunkLock_FullMethodName      = "/shardedmc.CoordinatorService/RequestChunkLock"
	CoordinatorService_ReleaseChunkLock_FullMethodName      = "/shardedmc.CoordinatorService/ReleaseChunkLock"
	CoordinatorService_SyncEntityState_FullMethodName       = "/shardedmc.CoordinatorService/SyncEntityState"
)

// CoordinatorServiceClient is the client API for CoordinatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Coordinator service
type CoordinatorServiceClient interface {
	RegisterShard(ctx context.Context, in *ShardInfo, opts ...grpc.CallOption) (*RegistrationResponse, error)
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	RequestPlayerTransfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	ConfirmPlayerTransfer(ctx context.Context, in *TransferConfirmation, opts ...grpc.CallOption) (*ConfirmationResponse, error)
	RequestChunkLoad(ctx context.Context, in *ChunkLoadRequest, opts ...grpc.CallOption) (*ChunkLoadResponse, error)
	RequestChunkUnload(ctx context.Context, in *ChunkUnloadRequest, opts ...grpc.CallOption) (*ChunkUnloadResponse, error)
	RequestChunkLock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error)
	ReleaseChunkLock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*Empty, error)
	SyncEntityState(ctx context.Context, in *EntityStateSync, opts ...grpc.CallOption) (*SyncResponse, error)
}

type coordinatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorServiceClient(cc grpc.ClientConnInterface) CoordinatorServiceClient {
	return &coordinatorServiceClient{cc}
}

func (c *coordinatorServiceClient) RegisterShard(ctx context.Context, in *ShardInfo, opts ...grpc.CallOption) (*RegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_RegisterShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) RequestPlayerTransfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_RequestPlayerTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) ConfirmPlayerTransfer(ctx context.Context, in *TransferConfirmation, opts ...grpc.CallOption) (*ConfirmationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmationResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_ConfirmPlayerTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) RequestChunkLoad(ctx context.Context, in *ChunkLoadRequest, opts ...grpc.CallOption) (*ChunkLoadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChunkLoadResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_RequestChunkLoad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) RequestChunkUnload(ctx context.Context, in *ChunkUnloadRequest, opts ...grpc.CallOption) (*ChunkUnloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChunkUnloadResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_RequestChunkUnload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) RequestChunkLock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_RequestChunkLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) ReleaseChunkLock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoordinatorService_ReleaseChunkLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) SyncEntityState(ctx context.Context, in *EntityStateSync, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_SyncEntityState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServiceServer is the server API for CoordinatorService service.
// All implementations must embed UnimplementedCoordinatorServiceServer
// for forward compatibility.
//
// Coordinator service
type CoordinatorServiceServer interface {
	RegisterShard(context.Context, *ShardInfo) (*RegistrationResponse, error)
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	RequestPlayerTransfer(context.Context, *TransferRequest) (*TransferResponse, error)
	ConfirmPlayerTransfer(context.Context, *TransferConfirmation) (*ConfirmationResponse, error)
	RequestChunkLoad(context.Context, *ChunkLoadRequest) (*ChunkLoadResponse, error)
	RequestChunkUnload(context.Context, *ChunkUnloadRequest) (*ChunkUnloadResponse, error)
	RequestChunkLock(context.Context, *LockRequest) (*LockResponse, error)
	ReleaseChunkLock(context.Context, *LockRequest) (*Empty, error)
	SyncEntityState(context.Context, *EntityStateSync) (*SyncResponse, error)
	mustEmbedUnimplementedCoordinatorServiceServer()
}

// UnimplementedCoordinatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorServiceServer struct{}

func (UnimplementedCoordinatorServiceServer) RegisterShard(context.Context, *ShardInfo) (*RegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterShard not implemented")
}
func (UnimplementedCoordinatorServiceServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedCoordinatorServiceServer) RequestPlayerTransfer(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestPlayerTransfer not implemented")
}
func (UnimplementedCoordinatorServiceServer) ConfirmPlayerTransfer(context.Context, *TransferConfirmation) (*ConfirmationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmPlayerTransfer not implemented")
}
func (UnimplementedCoordinatorServiceServer) RequestChunkLoad(context.Context, *ChunkLoadRequest) (*ChunkLoadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestChunkLoad not implemented")
}
func (UnimplementedCoordinatorServiceServer) RequestChunkUnload(context.Context, *ChunkUnloadRequest) (*ChunkUnloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestChunkUnload not implemented")
}
func (UnimplementedCoordinatorServiceServer) RequestChunkLock(context.Context, *LockRequest) (*LockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestChunkLock not implemented")
}
func (UnimplementedCoordinatorServiceServer) ReleaseChunkLock(context.Context, *LockRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseChunkLock not implemented")
}
func (UnimplementedCoordinatorServiceServer) SyncEntityState(context.Context, *EntityStateSync) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncEntityState not implemented")
}
func (UnimplementedCoordinatorServiceServer) mustEmbedUnimplementedCoordinatorServiceServer() {}
func (UnimplementedCoordinatorServiceServer) testEmbeddedByValue()                            {}

// UnsafeCoordinatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServiceServer will
// result in compilation errors.
type UnsafeCoordinatorServiceServer interface {
	mustEmbedUnimplementedCoordinatorServiceServer()
}

func RegisterCoordinatorServiceServer(s grpc.ServiceRegistrar, srv CoordinatorServiceServer) {
	// If the following call panics, it indicates UnimplementedCoordinatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinatorService_ServiceDesc, srv)
}

func _CoordinatorService_RegisterShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShardInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).RegisterShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_RegisterShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).RegisterShard(ctx, req.(*ShardInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_RequestPlayerTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).RequestPlayerTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_RequestPlayerTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).RequestPlayerTransfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_ConfirmPlayerTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferConfirmation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).ConfirmPlayerTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_ConfirmPlayerTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).ConfirmPlayerTransfer(ctx, req.(*TransferConfirmation))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_RequestChunkLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkLoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).RequestChunkLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_RequestChunkLoad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).RequestChunkLoad(ctx, req.(*ChunkLoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_RequestChunkUnload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkUnloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).RequestChunkUnload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_RequestChunkUnload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).RequestChunkUnload(ctx, req.(*ChunkUnloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_RequestChunkLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).RequestChunkLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_RequestChunkLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).RequestChunkLock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_ReleaseChunkLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).ReleaseChunkLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_ReleaseChunkLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).ReleaseChunkLock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_SyncEntityState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityStateSync)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).SyncEntityState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_SyncEntityState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).SyncEntityState(ctx, req.(*EntityStateSync))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinatorService_ServiceDesc is the grpc.ServiceDesc for CoordinatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shardedmc.CoordinatorService",
	HandlerType: (*CoordinatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterShard",
			Handler:    _CoordinatorService_RegisterShard_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _CoordinatorService_SendHeartbeat_Handler,
		},
		{
			MethodName: "RequestPlayerTransfer",
			Handler:    _CoordinatorService_RequestPlayerTransfer_Handler,
		},
		{
			MethodName: "ConfirmPlayerTransfer",
			Handler:    _CoordinatorService_ConfirmPlayerTransfer_Handler,
		},
		{
			MethodName: "RequestChunkLoad",
			Handler:    _CoordinatorService_RequestChunkLoad_Handler,
		},
		{
			MethodName: "RequestChunkUnload",
			Handler:    _CoordinatorService_RequestChunkUnload_Handler,
		},
		{
			MethodName: "RequestChunkLock",
			Handler:    _CoordinatorService_RequestChunkLock_Handler,
		},
		{
			MethodName: "ReleaseChunkLock",
			Handler:    _CoordinatorService_ReleaseChunkLock_Handler,
		},
		{
			MethodName: "SyncEntityState",
			Handler:    _CoordinatorService_SyncEntityState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/coordinator.proto",
}
