// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/proto/coordinator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common messages
type Vec3D struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec3D) Reset() {
	*x = Vec3D{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec3D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec3D) ProtoMessage() {}

func (x *Vec3D) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec3D.ProtoReflect.Descriptor instead.
func (*Vec3D) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *Vec3D) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec3D) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vec3D) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Vec3I struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             int32                  `protobuf:"varint,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec3I) Reset() {
	*x = Vec3I{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec3I) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec3I) ProtoMessage() {}

func (x *Vec3I) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec3I.ProtoReflect.Descriptor instead.
func (*Vec3I) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *Vec3I) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec3I) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vec3I) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type ChunkPos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Z             int32                  `protobuf:"varint,2,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkPos) Reset() {
	*x = ChunkPos{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkPos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkPos) ProtoMessage() {}

func (x *ChunkPos) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkPos.ProtoReflect.Descriptor instead.
func (*ChunkPos) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkPos) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ChunkPos) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Position      *Vec3D                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Velocity      *Vec3D                 `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Health        float64                `protobuf:"fixed64,5,opt,name=health,proto3" json:"health,omitempty"`
	Inventory     []byte                 `protobuf:"bytes,6,opt,name=inventory,proto3" json:"inventory,omitempty"`
	GameMode      int32                  `protobuf:"varint,7,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerState) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PlayerState) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerState) GetPosition() *Vec3D {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerState) GetVelocity() *Vec3D {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *PlayerState) GetHealth() float64 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *PlayerState) GetInventory() []byte {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *PlayerState) GetGameMode() int32 {
	if x != nil {
		return x.GameMode
	}
	return 0
}

func (x *PlayerState) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EntityState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Position      *Vec3D                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Velocity      *Vec3D                 `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Health        float64                `protobuf:"fixed64,5,opt,name=health,proto3" json:"health,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityState) Reset() {
	*x = EntityState{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityState) ProtoMessage() {}

func (x *EntityState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityState.ProtoReflect.Descriptor instead.
func (*EntityState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *EntityState) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *EntityState) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EntityState) GetPosition() *Vec3D {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EntityState) GetVelocity() *Vec3D {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *EntityState) GetHealth() float64 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *EntityState) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Shard registration
type ShardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Regions       []*ChunkPos            `protobuf:"bytes,5,rep,name=regions,proto3" json:"regions,omitempty"`
	Token         string                 `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardInfo) Reset() {
	*x = ShardInfo{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardInfo) ProtoMessage() {}

func (x *ShardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardInfo.ProtoReflect.Descriptor instead.
func (*ShardInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *ShardInfo) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ShardInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ShardInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ShardInfo) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *ShardInfo) GetRegions() []*ChunkPos {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *ShardInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegistrationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AssignedRegions []*ChunkPos            `protobuf:"bytes,3,rep,name=assigned_regions,json=assignedRegions,proto3" json:"assigned_regions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *RegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegistrationResponse) GetAssignedRegions() []*ChunkPos {
	if x != nil {
		return x.AssignedRegions
	}
	return nil
}

// Heartbeat
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Load          float64                `protobuf:"fixed64,2,opt,name=load,proto3" json:"load,omitempty"`
	PlayerCount   int32                  `protobuf:"varint,3,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	MemoryUsageMb int32                  `protobuf:"varint,4,opt,name=memory_usage_mb,json=memoryUsageMb,proto3" json:"memory_usage_mb,omitempty"`
	Regions       []*ChunkPos            `protobuf:"bytes,5,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *HeartbeatRequest) GetLoad() float64 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *HeartbeatRequest) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *HeartbeatRequest) GetMemoryUsageMb() int32 {
	if x != nil {
		return x.MemoryUsageMb
	}
	return 0
}

func (x *HeartbeatRequest) GetRegions() []*ChunkPos {
	if x != nil {
		return x.Regions
	}
	return nil
}

type HeartbeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Healthy        bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Reassignments  []*ChunkPos            `protobuf:"bytes,2,rep,name=reassignments,proto3" json:"reassignments,omitempty"`
	ShouldShutdown bool                   `protobuf:"varint,3,opt,name=should_shutdown,json=shouldShutdown,proto3" json:"should_shutdown,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HeartbeatResponse) GetReassignments() []*ChunkPos {
	if x != nil {
		return x.Reassignments
	}
	return nil
}

func (x *HeartbeatResponse) GetShouldShutdown() bool {
	if x != nil {
		return x.ShouldShutdown
	}
	return false
}

// Player transfer
type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerUuid    string                 `protobuf:"bytes,1,opt,name=player_uuid,json=playerUuid,proto3" json:"player_uuid,omitempty"`
	SourceShardId string                 `protobuf:"bytes,2,opt,name=source_shard_id,json=sourceShardId,proto3" json:"source_shard_id,omitempty"`
	TargetShardId string                 `protobuf:"bytes,3,opt,name=target_shard_id,json=targetShardId,proto3" json:"target_shard_id,omitempty"`
	PlayerState   *PlayerState           `protobuf:"bytes,4,opt,name=player_state,json=playerState,proto3" json:"player_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *TransferRequest) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

func (x *TransferRequest) GetSourceShardId() string {
	if x != nil {
		return x.SourceShardId
	}
	return ""
}

func (x *TransferRequest) GetTargetShardId() string {
	if x != nil {
		return x.TargetShardId
	}
	return ""
}

func (x *TransferRequest) GetPlayerState() *PlayerState {
	if x != nil {
		return x.PlayerState
	}
	return nil
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *TransferResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *TransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TransferConfirmation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerUuid    string                 `protobuf:"bytes,1,opt,name=player_uuid,json=playerUuid,proto3" json:"player_uuid,omitempty"`
	SourceShardId string                 `protobuf:"bytes,2,opt,name=source_shard_id,json=sourceShardId,proto3" json:"source_shard_id,omitempty"`
	TargetShardId string                 `protobuf:"bytes,3,opt,name=target_shard_id,json=targetShardId,proto3" json:"target_shard_id,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferConfirmation) Reset() {
	*x = TransferConfirmation{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferConfirmation) ProtoMessage() {}

func (x *TransferConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferConfirmation.ProtoReflect.Descriptor instead.
func (*TransferConfirmation) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{11}
}

func (x *TransferConfirmation) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

func (x *TransferConfirmation) GetSourceShardId() string {
	if x != nil {
		return x.SourceShardId
	}
	return ""
}

func (x *TransferConfirmation) GetTargetShardId() string {
	if x != nil {
		return x.TargetShardId
	}
	return ""
}

func (x *TransferConfirmation) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ConfirmationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmationResponse) Reset() {
	*x = ConfirmationResponse{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmationResponse) ProtoMessage() {}

func (x *ConfirmationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmationResponse.ProtoReflect.Descriptor instead.
func (*ConfirmationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{12}
}

func (x *ConfirmationResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// Chunk management
type ChunkLoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	ChunkPos      *ChunkPos              `protobuf:"bytes,2,opt,name=chunk_pos,json=chunkPos,proto3" json:"chunk_pos,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkLoadRequest) Reset() {
	*x = ChunkLoadRequest{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkLoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkLoadRequest) ProtoMessage() {}

func (x *ChunkLoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkLoadRequest.ProtoReflect.Descriptor instead.
func (*ChunkLoadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{13}
}

func (x *ChunkLoadRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ChunkLoadRequest) GetChunkPos() *ChunkPos {
	if x != nil {
		return x.ChunkPos
	}
	return nil
}

func (x *ChunkLoadRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type ChunkLoadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OwnerShardId  string                 `protobuf:"bytes,2,opt,name=owner_shard_id,json=ownerShardId,proto3" json:"owner_shard_id,omitempty"`
	ChunkData     []byte                 `protobuf:"bytes,3,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkLoadResponse) Reset() {
	*x = ChunkLoadResponse{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkLoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkLoadResponse) ProtoMessage() {}

func (x *ChunkLoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkLoadResponse.ProtoReflect.Descriptor instead.
func (*ChunkLoadResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{14}
}

func (x *ChunkLoadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChunkLoadResponse) GetOwnerShardId() string {
	if x != nil {
		return x.OwnerShardId
	}
	return ""
}

func (x *ChunkLoadResponse) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

type ChunkUnloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	ChunkPos      *ChunkPos              `protobuf:"bytes,2,opt,name=chunk_pos,json=chunkPos,proto3" json:"chunk_pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUnloadRequest) Reset() {
	*x = ChunkUnloadRequest{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUnloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUnloadRequest) ProtoMessage() {}

func (x *ChunkUnloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUnloadRequest.ProtoReflect.Descriptor instead.
func (*ChunkUnloadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{15}
}

func (x *ChunkUnloadRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ChunkUnloadRequest) GetChunkPos() *ChunkPos {
	if x != nil {
		return x.ChunkPos
	}
	return nil
}

type ChunkUnloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUnloadResponse) Reset() {
	*x = ChunkUnloadResponse{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUnloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUnloadResponse) ProtoMessage() {}

func (x *ChunkUnloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUnloadResponse.ProtoReflect.Descriptor instead.
func (*ChunkUnloadResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{16}
}

func (x *ChunkUnloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Chunk locking
type LockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	ChunkPos      *ChunkPos              `protobuf:"bytes,2,opt,name=chunk_pos,json=chunkPos,proto3" json:"chunk_pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequest.ProtoReflect.Descriptor instead.
func (*LockRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{17}
}

func (x *LockRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *LockRequest) GetChunkPos() *ChunkPos {
	if x != nil {
		return x.ChunkPos
	}
	return nil
}

type LockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OwnerShardId  string                 `protobuf:"bytes,2,opt,name=owner_shard_id,json=ownerShardId,proto3" json:"owner_shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockResponse) Reset() {
	*x = LockResponse{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockResponse) ProtoMessage() {}

func (x *LockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockResponse.ProtoReflect.Descriptor instead.
func (*LockResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{18}
}

func (x *LockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LockResponse) GetOwnerShardId() string {
	if x != nil {
		return x.OwnerShardId
	}
	return ""
}

// Empty message for methods that don't need parameters
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{19}
}

// Entity sync
type EntityStateSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Entities      []*EntityState         `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	Delta         bool                   `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityStateSync) Reset() {
	*x = EntityStateSync{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityStateSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityStateSync) ProtoMessage() {}

func (x *EntityStateSync) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityStateSync.ProtoReflect.Descriptor instead.
func (*EntityStateSync) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{20}
}

func (x *EntityStateSync) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *EntityStateSync) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *EntityStateSync) GetDelta() bool {
	if x != nil {
		return x.Delta
	}
	return false
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SyncedCount   int32                  `protobuf:"varint,2,opt,name=synced_count,json=syncedCount,proto3" json:"synced_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_pkg_proto_coordinator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_coordinator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_coordinator_proto_rawDescGZIP(), []int{21}
}

func (x *SyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncResponse) GetSyncedCount() int32 {
	if x != nil {
		return x.SyncedCount
	}
	return 0
}

var File_pkg_proto_coordinator_proto protoreflect.FileDescriptor

const file_pkg_proto_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/proto/coordinator.proto\x12\tshardedmc\"1\n" +
	"\x05Vec3d\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\"1\n" +
	"\x05Vec3i\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x05R\x01z\"&\n" +
	"\bChunkPos\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01z\x18\x02 \x01(\x05R\x01z\"\x88\x02\n" +
	"\vPlayerState\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12,\n" +
	"\bposition\x18\x03 \x01(\v2\x10.shardedmc.Vec3dR\bposition\x12,\n" +
	"\bvelocity\x18\x04 \x01(\v2\x10.shardedmc.Vec3dR\bvelocity\x12\x16\n" +
	"\x06health\x18\x05 \x01(\x01R\x06health\x12\x1c\n" +
	"\tinventory\x18\x06 \x01(\fR\tinventory\x12\x1b\n" +
	"\tgame_mode\x18\a \x01(\x05R\bgameMode\x12\x1a\n" +
	"\bmetadata\x18\b \x01(\fR\bmetadata\"\xc5\x01\n" +
	"\vEntityState\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12,\n" +
	"\bposition\x18\x03 \x01(\v2\x10.shardedmc.Vec3dR\bposition\x12,\n" +
	"\bvelocity\x18\x04 \x01(\v2\x10.shardedmc.Vec3dR\bvelocity\x12\x16\n" +
	"\x06health\x18\x05 \x01(\x01R\x06health\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\fR\bmetadata\"\xb5\x01\n" +
	"\tShardInfo\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\x12-\n" +
	"\aregions\x18\x05 \x03(\v2\x13.shardedmc.ChunkPosR\aregions\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\"\x8a\x01\n" +
	"\x14RegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\x10assigned_regions\x18\x03 \x03(\v2\x13.shardedmc.ChunkPosR\x0fassignedRegions\"\xbb\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x12\n" +
	"\x04load\x18\x02 \x01(\x01R\x04load\x12!\n" +
	"\fplayer_count\x18\x03 \x01(\x05R\vplayerCount\x12&\n" +
	"\x0fmemory_usage_mb\x18\x04 \x01(\x05R\rmemoryUsageMb\x12-\n" +
	"\aregions\x18\x05 \x03(\v2\x13.shardedmc.ChunkPosR\aregions\"\x91\x01\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x129\n" +
	"\rreassignments\x18\x02 \x03(\v2\x13.shardedmc.ChunkPosR\rreassignments\x12'\n" +
	"\x0fshould_shutdown\x18\x03 \x01(\bR\x0eshouldShutdown\"\xbd\x01\n" +
	"\x0fTransferRequest\x12\x1f\n" +
	"\vplayer_uuid\x18\x01 \x01(\tR\n" +
	"playerUuid\x12&\n" +
	"\x0fsource_shard_id\x18\x02 \x01(\tR\rsourceShardId\x12&\n" +
	"\x0ftarget_shard_id\x18\x03 \x01(\tR\rtargetShardId\x129\n" +
	"\fplayer_state\x18\x04 \x01(\v2\x16.shardedmc.PlayerStateR\vplayerState\"H\n" +
	"\x10TransferResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa1\x01\n" +
	"\x14TransferConfirmation\x12\x1f\n" +
	"\vplayer_uuid\x18\x01 \x01(\tR\n" +
	"playerUuid\x12&\n" +
	"\x0fsource_shard_id\x18\x02 \x01(\tR\rsourceShardId\x12&\n" +
	"\x0ftarget_shard_id\x18\x03 \x01(\tR\rtargetShardId\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\":\n" +
	"\x14ConfirmationResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"u\n" +
	"\x10ChunkLoadRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x120\n" +
	"\tchunk_pos\x18\x02 \x01(\v2\x13.shardedmc.ChunkPosR\bchunkPos\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"r\n" +
	"\x11ChunkLoadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12$\n" +
	"\x0eowner_shard_id\x18\x02 \x01(\tR\fownerShardId\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x03 \x01(\fR\tchunkData\"a\n" +
	"\x12ChunkUnloadRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x120\n" +
	"\tchunk_pos\x18\x02 \x01(\v2\x13.shardedmc.ChunkPosR\bchunkPos\"/\n" +
	"\x13ChunkUnloadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Z\n" +
	"\vLockRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x120\n" +
	"\tchunk_pos\x18\x02 \x01(\v2\x13.shardedmc.ChunkPosR\bchunkPos\"N\n" +
	"\fLockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12$\n" +
	"\x0eowner_shard_id\x18\x02 \x01(\tR\fownerShardId\"\a\n" +
	"\x05Empty\"v\n" +
	"\x0fEntityStateSync\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x122\n" +
	"\bentities\x18\x02 \x03(\v2\x16.shardedmc.EntityStateR\bentities\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\bR\x05delta\"K\n" +
	"\fSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fsynced_count\x18\x02 \x01(\x05R\vsyncedCount2\xc4\x05\n" +
	"\x12CoordinatorService\x12F\n" +
	"\rRegisterShard\x12\x14.shardedmc.ShardInfo\x1a\x1f.shardedmc.RegistrationResponse\x12J\n" +
	"\rSendHeartbeat\x12\x1b.shardedmc.HeartbeatRequest\x1a\x1c.shardedmc.HeartbeatResponse\x12P\n" +
	"\x15RequestPlayerTransfer\x12\x1a.shardedmc.TransferRequest\x1a\x1b.shardedmc.TransferResponse\x12Y\n" +
	"\x15ConfirmPlayerTransfer\x12\x1f.shardedmc.TransferConfirmation\x1a\x1f.shardedmc.ConfirmationResponse\x12M\n" +
	"\x10RequestChunkLoad\x12\x1b.shardedmc.ChunkLoadRequest\x1a\x1c.shardedmc.ChunkLoadResponse\x12S\n" +
	"\x12RequestChunkUnload\x12\x1d.shardedmc.ChunkUnloadRequest\x1a\x1e.shardedmc.ChunkUnloadResponse\x12C\n" +
	"\x10RequestChunkLock\x12\x16.shardedmc.LockRequest\x1a\x17.shardedmc.LockResponse\x12<\n" +
	"\x10ReleaseChunkLock\x12\x16.shardedmc.LockRequest\x1a\x10.shardedmc.Empty\x12F\n" +
	"\x0fSyncEntityState\x12\x1a.shardedmc.EntityStateSync\x1a\x17.shardedmc.SyncResponseBU\n" +
	"\x13com.shardedmc.protoB\x10CoordinatorProtoP\x01Z*github.com/shardedmc/coordinator/pkg/protob\x06proto3"

var (
	file_pkg_proto_coordinator_proto_rawDescOnce sync.Once
	file_pkg_proto_coordinator_proto_rawDescData []byte
)

func file_pkg_proto_coordinator_proto_rawDescGZIP() []byte {
	file_pkg_proto_coordinator_proto_rawDescOnce.Do(func() {
		file_pkg_proto_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_coordinator_proto_rawDesc), len(file_pkg_proto_coordinator_proto_rawDesc)))
	})
	return file_pkg_proto_coordinator_proto_rawDescData
}

var file_pkg_proto_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_pkg_proto_coordinator_proto_goTypes = []any{
	(*Vec3D)(nil),                // 0: shardedmc.Vec3d
	(*Vec3I)(nil),                // 1: shardedmc.Vec3i
	(*ChunkPos)(nil),             // 2: shardedmc.ChunkPos
	(*PlayerState)(nil),          // 3: shardedmc.PlayerState
	(*EntityState)(nil),          // 4: shardedmc.EntityState
	(*ShardInfo)(nil),            // 5: shardedmc.ShardInfo
	(*RegistrationResponse)(nil), // 6: shardedmc.RegistrationResponse
	(*HeartbeatRequest)(nil),     // 7: shardedmc.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 8: shardedmc.HeartbeatResponse
	(*TransferRequest)(nil),      // 9: shardedmc.TransferRequest
	(*TransferResponse)(nil),     // 10: shardedmc.TransferResponse
	(*TransferConfirmation)(nil), // 11: shardedmc.TransferConfirmation
	(*ConfirmationResponse)(nil), // 12: shardedmc.ConfirmationResponse
	(*ChunkLoadRequest)(nil),     // 13: shardedmc.ChunkLoadRequest
	(*ChunkLoadResponse)(nil),    // 14: shardedmc.ChunkLoadResponse
	(*ChunkUnloadRequest)(nil),   // 15: shardedmc.ChunkUnloadRequest
	(*ChunkUnloadResponse)(nil),  // 16: shardedmc.ChunkUnloadResponse
	(*LockRequest)(nil),          // 17: shardedmc.LockRequest
	(*LockResponse)(nil),         // 18: shardedmc.LockResponse
	(*Empty)(nil),                // 19: shardedmc.Empty
	(*EntityStateSync)(nil),      // 20: shardedmc.EntityStateSync
	(*SyncResponse)(nil),         // 21: shardedmc.SyncResponse
}
var file_pkg_proto_coordinator_proto_depIdxs = []int32{
	0,  // 0: shardedmc.PlayerState.position:type_name -> shardedmc.Vec3d
	0,  // 1: shardedmc.PlayerState.velocity:type_name -> shardedmc.Vec3d
	0,  // 2: shardedmc.EntityState.position:type_name -> shardedmc.Vec3d
	0,  // 3: shardedmc.EntityState.velocity:type_name -> shardedmc.Vec3d
	2,  // 4: shardedmc.ShardInfo.regions:type_name -> shardedmc.ChunkPos
	2,  // 5: shardedmc.RegistrationResponse.assigned_regions:type_name -> shardedmc.ChunkPos
	2,  // 6: shardedmc.HeartbeatRequest.regions:type_name -> shardedmc.ChunkPos
	2,  // 7: shardedmc.HeartbeatResponse.reassignments:type_name -> shardedmc.ChunkPos
	3,  // 8: shardedmc.TransferRequest.player_state:type_name -> shardedmc.PlayerState
	2,  // 9: shardedmc.ChunkLoadRequest.chunk_pos:type_name -> shardedmc.ChunkPos
	2,  // 10: shardedmc.ChunkUnloadRequest.chunk_pos:type_name -> shardedmc.ChunkPos
	2,  // 11: shardedmc.LockRequest.chunk_pos:type_name -> shardedmc.ChunkPos
	4,  // 12: shardedmc.EntityStateSync.entities:type_name -> shardedmc.EntityState
	5,  // 13: shardedmc.CoordinatorService.RegisterShard:input_type -> shardedmc.ShardInfo
	7,  // 14: shardedmc.CoordinatorService.SendHeartbeat:input_type -> shardedmc.HeartbeatRequest
	9,  // 15: shardedmc.CoordinatorService.RequestPlayerTransfer:input_type -> shardedmc.TransferRequest
	11, // 16: shardedmc.CoordinatorService.ConfirmPlayerTransfer:input_type -> shardedmc.TransferConfirmation
	13, // 17: shardedmc.CoordinatorService.RequestChunkLoad:input_type -> shardedmc.ChunkLoadRequest
	15, // 18: shardedmc.CoordinatorService.RequestChunkUnload:input_type -> shardedmc.ChunkUnloadRequest
	17, // 19: shardedmc.CoordinatorService.RequestChunkLock:input_type -> shardedmc.LockRequest
	17, // 20: shardedmc.CoordinatorService.ReleaseChunkLock:input_type -> shardedmc.LockRequest
	20, // 21: shardedmc.CoordinatorService.SyncEntityState:input_type -> shardedmc.EntityStateSync
	6,  // 22: shardedmc.CoordinatorService.RegisterShard:output_type -> shardedmc.RegistrationResponse
	8,  // 23: shardedmc.CoordinatorService.SendHeartbeat:output_type -> shardedmc.HeartbeatResponse
	10, // 24: shardedmc.CoordinatorService.RequestPlayerTransfer:output_type -> shardedmc.TransferResponse
	12, // 25: shardedmc.CoordinatorService.ConfirmPlayerTransfer:output_type -> shardedmc.ConfirmationResponse
	14, // 26: shardedmc.CoordinatorService.RequestChunkLoad:output_type -> shardedmc.ChunkLoadResponse
	16, // 27: shardedmc.CoordinatorService.RequestChunkUnload:output_type -> shardedmc.ChunkUnloadResponse
	18, // 28: shardedmc.CoordinatorService.RequestChunkLock:output_type -> shardedmc.LockResponse
	19, // 29: shardedmc.CoordinatorService.ReleaseChunkLock:output_type -> shardedmc.Empty
	21, // 30: shardedmc.CoordinatorService.SyncEntityState:output_type -> shardedmc.SyncResponse
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_pkg_proto_coordinator_proto_init() }
func file_pkg_proto_coordinator_proto_init() {
	if File_pkg_proto_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_coordinator_proto_rawDesc), len(file_pkg_proto_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_coordinator_proto_goTypes,
		DependencyIndexes: file_pkg_proto_coordinator_proto_depIdxs,
		MessageInfos:      file_pkg_proto_coordinator_proto_msgTypes,
	}.Build()
	File_pkg_proto_coordinator_proto = out.File
	file_pkg_proto_coordinator_proto_goTypes = nil
	file_pkg_proto_coordinator_proto_depIdxs = nil
}
